name:                csview
version:             0.1.0.0
github:              "peteryland/csview"
license:             BSD3
author:              "Pete Ryland"
maintainer:          "pdr@pdr.cx"
copyright:           "(c) 2019 Pete Ryland"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A command-line CSV viewer
category:            Tools
description:         Please see the README on GitHub at <https://github.com/peteryland/csview#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 0.1
- ansi-terminal >= 0.8

executables:
  csv:
    main:                Main.hs
    source-dirs:
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    dependencies:
    - parsec
